logging:
  level:
    com.autocat.maplestory.openapi.nexon: DEBUG

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full



