logging:
  level:
    com.autocat.nexonopenapi: DEBUG

spring:
  datasource:
    url: jdbc:mysql://${PUBLIC_IP:localhost}:43306/omm?serverTimezone=Asia/Seoul
    username: omm
    password: omm!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full



